### ISSUE TITLE
Problem kiedy źródłem anime jest cda

### ISSUE THREAD

**Issue by SoWhat84** [Lantash77/lantash-repo#1]
Tak jak w temacie. Szukając anime na shinden, wybierając źródło CDA, plik na początku się ładuje, ale nie buforuje się dalej. Więc po kilku sekundach odtwarzania, dochodzi do zawieszenia się KODI. Używam KODI 19 na Windows 10.

**Comment by Lantash77** [comment]
Witam. Sprawdź logi. Zaktualizuj resolveurl. Generalnie wtyczka nie ma wpływu na odtwarzanie i buforowanie. Wysyła link do resolvera. Problem musi być gdzie indziej. Niektóre źródła CDA na Shinden kuleją szczególnie przy starszych tytułach
