### ISSUE TITLE
[shinden.pl] Błąd - "Nieudane odtwarzanie jednej lub więcej pozycji."

### ISSUE THREAD

**Issue by etharos** [Lantash77/lantash-repo#11]
Wersja Kodi 20.1 / Anime Otaku 0.1.19.0

Problem dotyczy anime-shinden.pl - parę dni działało wszystko bez problemu, jednak któregoś dnia przestało. Nic nie aktualizowałem - więc zakładam, że coś po stronie anime-shinden.pl się zmieniło (strona nadal działa za pomocą przeglądarki). Kolegę pytałem który też korzysta z Kodiego i Anime Otaku i ma dokładnie ten sam problem.

Podczas próby włączenia odcinka z ulubionych z shinden.pl po wczytaniu listy odcinków a następnie próby odtworzenia odcinka (lista dostępnych źródeł się jeszcze nie wczytała), to pojawia się komunikat:

"Nieudane odtwarzanie jednej lub więcej pozycji. Więcej informacji na ten temat znajdziesz w pliku dziennika zdarzeń."

Natomiast po próbie wejścia w shinden.pl w celu wyszukania czegokolwiek pojawia się błąd "Błąd anime Otaku. Więcej informacji na ten temat znajdziesz w pliku dziennika zdarzeń."

Próbowałem znaleźć z poziomu Kodi ten log, jednak po wejściu w "Ustawienia" -> "Dziennik zdarzeń" mam tylko wyświetlają informację o "Uruchomienie Kodi zakończone powodzeniem."

PS  Sprawdzałem czy reszta serwisów, które nie wymajają logowania czy działa i działają poza - wbijam.pl tam po otworzeniu serwisu w celu czegoś wyszukania pojawia się po prostu okienko, bez możliwości kliknięcia czegokolwiek.

**Comment by Lantash77** [comment]
Fix do shinden jest od wczoraj (0.1.20)
Rzucę okiem na wbijam.pl w czasie weekendu.

**Comment by etharos** [comment]
Dodam od siebie, że na wersji 0.1.20 - wbijam.pl działało poprawnie.

**Comment by Lantash77** [comment]
@etharos zgadza się, z tym że, ostatni komunikat na stronie podaje o awarii serwera i zmianie serwera na wbijam.pl.
Strona po ponownym uruchomieniu domyślnie ukryta była za CF - była potrzeba nawiązania kontaktu z adminem strony, żeby znaleźć rozwiazanie.
Na szczęście bardzo sympatyczny gość i pomógł bez problemu.
