### ISSUE TITLE
[StrefaDB] linki VIP

### ISSUE THREAD

**Issue by Khaagar** [Lantash77/lantash-repo#12]
Cześć, czy jest możliwość wyłapania linków VIP ze strefy DB jeżeli użytkownik ma aktywna subskrypcję?

**Comment by Lantash77** [comment]
Niestety nie mam subskrypcji, żeby to wychwycić i obrobić.

**Comment by Khaagar** [comment]
VIP na dzień to 33grosze, można BLIKnąć, ewentualnie powiedz czego potrzebujesz, to spróbuję wyciągnąć ze źródeł.

**Comment by Lantash77** [comment]
Niestety nie mam jak BLIKnąć z powodu lokacji, 
Jeżeli możesz pomóc wyciągnąć - to zapraszam na priv DC Lantash#1155
