### ISSUE TITLE
drama queen k20.1

### ISSUE THREAD

**Issue by anon2018** [Lantash77/lantash-repo#13]
http://paste.ubuntu.com/p/5JWxVRdwgy/

od tygodnia prawie zona sapie za dramami, ze linki nie odpalaja na k19, a po zmianie na k20 wtyczka nie odpala wcale, na wszelki nawet zmienilem haslo i wpisalem nowe bo myslalem, ze cos zle wpisuje czy cos

**Comment by Lantash77** [comment]
Wtyczka działa bez problemu. 
Podaj może przykładowy tytuł, który nie wchodzi.
Może ISA musi być zaktualizowane.
W Twoim logu nie widzę błędów wtyczki.

**Comment by anon2018** [comment]
jak wroce z pracy to sie postaram siasc

**Comment by Lantash77** [comment]
W K20 - może się zdarzyć problem z uruchomieniem linku. 
Można tymczasowo wyłaczyć integrację z upnext w ustawieniach i restart KODI. Do czasu aż namierzę i rozwiążę problem.
