### ISSUE TITLE
Problem przy wtyczce Anime Otaku z platformą wbijam.pl

### ISSUE THREAD

**Issue by retromaniak** [Lantash77/lantash-repo#2]
Dzień dobry,
Zainstalowałem wtyczkę waszego autorstwa do Kodi 19.4.0 będącym częścią systemu batocera.linux v35. Ogólnie wszystko działa dobrze za wyjątkiem wbijam.pl

O ile serie są przypisane do kategorii „akcja” lub „lżejsze klimaty” uruchamiają się prawidłowo, o tyle gdy chcę uruchomić coś z kategorii „dostępne serie anime” to system wyrzuca mnie z Kodi do ekranu głównego batocery. Wywalenie Kodi ma miejsce w momencie próby wyboru serii którą chcę odtworzyć, czyli jak się domyślam w momencie gdy wtyczka chce zaczytać listę odcinków/filmów.

Pod linkiem dołączam [zawartość pliku kodi.log](https://paste.kodi.tv/sicunumeku).

**Comment by Lantash77** [comment]
Możesz pełny log wysłać?

**Comment by retromaniak** [comment]
Jeżeli ogarnę to jak najbardziej. Zaraz sprawdzę czy dam radę.

**Comment by Lantash77** [comment]
W ustawieniach Kodi
System/Diagnostyka/ włączyć "rejestruj komunikaty diagnostyczne"
Wtedy spróbować uruchomić wtyczkę i funkcje która się wysypuje.
Wrzucić log.

Później można oczywiście wyłączyć logowanie.
Z loga który jest teraz, niewiele można odczytać.
Pozdrawiam

**Comment by retromaniak** [comment]
Ok to chyba udało mi się zrobić... Plik ma nie w okolicach 50-60kb a 170 więc wnioskuję że będzie dobrze
https://drive.google.com/file/d/1NzG7VMPXX06dnXDarR8rivbt1D6_2-6X/view?usp=drivesdk

**Comment by retromaniak** [comment]
Dziękuję za informację. Spróbuję zrobić downgrade. O ile nie wykrzaczą mi się inne funkcje.

**Comment by retromaniak** [comment]
Właśnie udało mi się zrobić rozeznanie. Niestety w systemie batocera nie ma możliwości downgrade'u Pythona dlatego też serdecznie dziękuję za okazaną pomoc jednak będę musiał poczekać na moment w którym wtyczka będzie przystosowana do pracy z pythonem 3.10 😢 

Mimo wszystko dziękuję za szybkie odpowiedzi i chęć pomocy tym komentarzem zamykam wątek gdyż problem na ten moment będzie nie do rozwiązania z przyczyn niezależnych.

Jeszcze raz dziękuję jednak za obsługę, gdyby wszyscy twórcy pluginów tak podchodzili do sprawy to świat byłby o wiele lepszy 😄
