### ISSUE TITLE
Anime Odcinki - nie pobiera źródeł

### ISSUE THREAD

**Issue by szczuru** [Lantash77/lantash-repo#22]
Tak jak w tytule, wczoraj tj 18.02.2024 wtyczka przestała wyświetlać źródła z Anime Odcinki. Przeszukiwać wszystko można lecz przy próbie odtwarzania wyświetla puste okno ze źródłami. Testowane na 20.4 na MiBoxie i czysta instalacja 20.4 + tylko Anime Otaku na Windowsie. Sama strona Anime Odcinki działa.

**Comment by Lantash77** [comment]
Poszedł fix. Sprawdź i daj znać.

**Comment by szczuru** [comment]
Śmiga, dziękuję :)

**Comment by szczuru** [comment]
Niestety znów padło i nie widzi źródeł :(
