### ISSUE TITLE
Prosba odnosnie  dodania opcji w settings

### ISSUE THREAD

**Issue by anon2018** [Lantash77/lantash-repo#24]
Kiedys wysadzilo cala wtyczke jak nie dzialala jedna strona, dodales "zabezpieczenie" by tak sie nie dzialo ale powoduje ono, ze wtyczka jest wolniejsza i powoduje problemy z otwieraniem anime po dodaniu do ulubionych, po prostu czasem laduje i zwraca pusta strone wiec trzeba wyjsc i wejsc ponownie, strefa db przez to szatkuje numerki ( do ponownego uruchomienia kodi ) na liscie i trzeba wchodzic przez dwa poziomy wtyczki by byly posortowane znowy i tak praktycznie bylo klikanie co odcinek na db super ( uzywam skory projekt aura, nie testowalem czy na innych dziala tak samo wiec to dopisze)

Czy dalo by sie w settings wtyczki dac ptaszka zaznacz odznacz do tego mechanizmu

**Comment by anon2018** [comment]
Uzywam twojej wtyczki codziennie, czesciej niz jakiej kolwiek innej

**Comment by Lantash77** [comment]
Nie zabezpieczenie jest tu przyczyną, aktualnie stopniowo aktualizuję kod pod API kodi20. 
Co może powodować, że niektóre pozycje zapisane w ulubionych, mogą mieć nieaktualne linki po zaktualizowaniu wtyczki. 
Na StrefaDB od dawna jakieś dziwne historie się dzieją z wyświetlaniem list.  NIe doszedłem co to powoduje, bo mechanika generowania i wyświetlania jest identyczna z pozostałymi hostami. Coś w Kodi się dziwnego dzieje i nie potrafię na tą chwilę tego wyłapać.
