### ISSUE TITLE
anime otaku

### ISSUE THREAD

**Issue by anon2018** [Lantash77/lantash-repo#3]
wtyczka padla na 19.5 android nie dziala, na czystym kodi to samo, zostawiam link do loga

https://pastebin.ubuntu.com/p/yWgzPVm4mX/
crash log

**Comment by Lantash77** [comment]
Wyłącz desu-online w ustawieniach.
Chyba włączyli cloudflare.
Wtyczka ma u nich bramkę, ale czasem zdarza się ze ja też zablokuje.
Nie przewidziałem że jeden serwis może cała wtyczkę wysypać.

**Comment by anon2018** [comment]
mowa o shindenie? czy ktorej stronie? nie lepiej by bylo odseparowac strony w osobnych wtyczkach? poza tym ciekawym pomyslem bylo by zrobienie animezone.pl maja wlotki szybciej niz shinden nawet, przypomnialem sobie tez , ze anime odcinki nie ma thumbinali co utrudnia zycie

**Comment by Lantash77** [comment]
W ustawieniach sekcja 'strony/konta' jest desu-online. Wyłącz to. Wtyczka zacznie działać.
Desu boryka się z jakąś awaria serwera.
Dodam poprawkę, która temu zapobiegnie w przyszłości.
Zamysł tej wtyczki był taki, żeby zebrać strony anime w jednej.
Trwają prace nad globalnym wyszukiwaniem.
Z dodaniem animezone przyjrzę się, bo przy tworzeniu wtyczki zrezygnowałem ze względu na brak świeżego kontentu, a to co mieli miało nieaktualne linki, lub braki w odcinkach.


________________________________

**Comment by anon2018** [comment]
czyli z fajna drama jest bunkracja, spoko... z animezone obserwuje od dluzszego czasu, od 2 sezonow sie poprawili, linki eng wstawiane godzine przed shindenem, linki pl tego co ma wysokie oceny z nowego sezonu tez z godizne przed shindenem a to co mniej lubiane max 4h po wyjsciu napisow, jest calkiem spoko

**Comment by anon2018** [comment]
anime-odcinki ma graafiki takie same dla kazdego odcinka, nie dasie zrobic tak zeby grafiki zasysalo z pierwszego odcinka? tak bys mogl chyba najprosciej to zrobic booni nie dodaja pustych zapewne

**Comment by Lantash77** [comment]
Niestety nie da się. Na listach tytułów na stronie nie ma żadnych grafik, które można użyć. Pierwszy plakat pojawia się dopiero na listach odcinków.
Pobieranie grafik z kolejnej strony zamuli wtyczkę, albo co gorzej, zablokuje hosta.

**Comment by anon2018** [comment]
a nie da sie zrobic cachowania obrazka po idpaleniu pierwszego odcinka?

**Comment by Lantash77** [comment]
Spróbuję - zobaczę co z tego wyjdzie.
________________________________

**Comment by Lantash77** [comment]
Dodany host animezone
Cachowanie postera w anime-odcinki
Fix po ostatniej awarii desu.pl - już nie wywala całej wtyczki
ba9cab70188d41b126b9427d9566842a2f770b9b

#
Zamykam
