### ISSUE TITLE
Wersja pluginu pod Kodi 20/Nexus?

### ISSUE THREAD

**Issue by NameLessJedi** [Lantash77/lantash-repo#4]
Hej,
planujesz może wersję pod v20?

**Comment by Lantash77** [comment]
Wszystkie wtyczki powinny działać pod K20.
Testowałem na WIN i Android. 
Możliwy nadmiar komunikatów w logu, ale to z czasem ogarnę.
Jak masz jakieś problemy na K20, napisz który plugin i przyślij log to coś się poradzi.

**Comment by NameLessJedi** [comment]
Działają :smile: 
Niesłusznie założyłem, że jak nie ma w repo v20 to nie będą działać.
Przepraszam za spam
