### ISSUE TITLE
Dodanie zabezpieczenia przed niedziałającymi serwerami

### ISSUE THREAD

**Issue by etharos** [Lantash77/lantash-repo#5]
Wersja Kodi 20 / Anime Otaku 0.1.18.0

Może warto dodać coś w postaci zabezpieczenia jeżeli jakiś serwer nie działa do którego próbuje się łączyć wtyczka. Parę dni temu po próbie odpalenia wtyczki wywalało mi komunikatem, że jest błąd i bym i w pliku logu został zapisany komunikat błędu (dodam, że w pliku logu kodiego nic nie było, chyba że wtyczka tworzy swój własny osobny).

Jak normalny człowiek po chwili walki zaorałem cały kodi i jeszcze raz zainstalowałem i znów nie działało ;) Dopiero ten post mnie naprowadził w czym jest problem - https://github.com/Lantash77/lantash-repo/issues/3

Szkoda, że właśnie nigdzie nie jest zaimplementowany ficzer, że jeżeli serwer/host jest wywalony to go z automatu pomija/wyłącza - albo chociaż komunikat. "Spróbuj wyłączyć serwisy z których nie korzystasz i sprawdź czy to rozwiążę problem".  :)

Ekstra robota z tą wtyczką :)

Pozdrawiam,
Herbaciarz

**Comment by etharos** [comment]
Doczytałem "Dodam poprawkę, która temu zapobiegnie w przyszłości." - temat można zostawić na rozwiązanie tego problemu :D

**Comment by Lantash77** [comment]
Poszła poprawka, awaria serwera nie wywala wtyczki.
