### ISSUE TITLE
Otaku kodi 20 zmiana w API

### ISSUE THREAD

**Issue by ilakatorz** [Lantash77/lantash-repo#6]
Zainstalowałem wtyczke otaku na android TV kodi 20, niestety nie uruchamia się przez błąd niżej. 

Error Contents: module 'xbmc' has no attribute 'translatePath'

Z tego co wiem translatePath jest już deprecated i trzeba ją zastąpić alternatywną funkcją, wątek niżej. 
https://github.com/xbmc/xbmc/pull/19301

**Comment by Lantash77** [comment]
Poszła poprawka, w wersji 0.1.18.1 
musiałem przeoczyć
